###############################################################################
# Created by write_sdc
# Tue Dec 12 03:25:34 2023
###############################################################################
current_design top_solo_squash
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 40.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_clock_latency -source -min 4.6500 [get_clocks {clk}]
set_clock_latency -source -max 5.5700 [get_clocks {clk}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {gpio_ready}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {gpio_ready}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[0]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[0]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[10]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[10]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[11]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[11]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[12]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[12]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[1]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[1]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[2]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[2]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[3]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[3]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[4]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[4]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[5]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[5]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[6]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[6]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[7]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[7]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[8]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[8]}]
set_input_delay 0.1800 -clock [get_clocks {clk}] -min -add_delay [get_ports {io_in[9]}]
set_input_delay 1.8700 -clock [get_clocks {clk}] -max -add_delay [get_ports {io_in[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.1900 [get_ports {io_out[12]}]
set_load -pin_load 0.1900 [get_ports {io_out[11]}]
set_load -pin_load 0.1900 [get_ports {io_out[10]}]
set_load -pin_load 0.1900 [get_ports {io_out[9]}]
set_load -pin_load 0.1900 [get_ports {io_out[8]}]
set_load -pin_load 0.1900 [get_ports {io_out[7]}]
set_load -pin_load 0.1900 [get_ports {io_out[6]}]
set_load -pin_load 0.1900 [get_ports {io_out[5]}]
set_load -pin_load 0.1900 [get_ports {io_out[4]}]
set_load -pin_load 0.1900 [get_ports {io_out[3]}]
set_load -pin_load 0.1900 [get_ports {io_out[2]}]
set_load -pin_load 0.1900 [get_ports {io_out[1]}]
set_load -pin_load 0.1900 [get_ports {io_out[0]}]
set_input_transition 0.6100 [get_ports {clk}]
set_input_transition -min 0.0700 [get_ports {gpio_ready}]
set_input_transition -max 0.8600 [get_ports {gpio_ready}]
set_input_transition -min 0.0500 [get_ports {io_in[12]}]
set_input_transition -max 0.3800 [get_ports {io_in[12]}]
set_input_transition -min 0.0500 [get_ports {io_in[11]}]
set_input_transition -max 0.3800 [get_ports {io_in[11]}]
set_input_transition -min 0.0500 [get_ports {io_in[10]}]
set_input_transition -max 0.3800 [get_ports {io_in[10]}]
set_input_transition -min 0.0500 [get_ports {io_in[9]}]
set_input_transition -max 0.3800 [get_ports {io_in[9]}]
set_input_transition -min 0.0500 [get_ports {io_in[8]}]
set_input_transition -max 0.3800 [get_ports {io_in[8]}]
set_input_transition -min 0.0500 [get_ports {io_in[7]}]
set_input_transition -max 0.3800 [get_ports {io_in[7]}]
set_input_transition -min 0.0500 [get_ports {io_in[6]}]
set_input_transition -max 0.3800 [get_ports {io_in[6]}]
set_input_transition -min 0.0500 [get_ports {io_in[5]}]
set_input_transition -max 0.3800 [get_ports {io_in[5]}]
set_input_transition -min 0.0500 [get_ports {io_in[4]}]
set_input_transition -max 0.3800 [get_ports {io_in[4]}]
set_input_transition -min 0.0500 [get_ports {io_in[3]}]
set_input_transition -max 0.3800 [get_ports {io_in[3]}]
set_input_transition -min 0.0500 [get_ports {io_in[2]}]
set_input_transition -max 0.3800 [get_ports {io_in[2]}]
set_input_transition -min 0.0500 [get_ports {io_in[1]}]
set_input_transition -max 0.3800 [get_ports {io_in[1]}]
set_input_transition -min 0.0500 [get_ports {io_in[0]}]
set_input_transition -max 0.3800 [get_ports {io_in[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 3.0000 [current_design]
set_max_fanout 4.0000 [current_design]
